### ISSUE TITLE
Providing the optional content on a Git repository

### ISSUE THREAD

**Issue by es20490446e** [Serosis/mm-hd#2]
I'm continuing here this [conversation](https://github.com/Serosis/UQM-MegaMod-Archived/issues/16). As once archived you cannot longer post there, and I have no other way to contact you. The link to your website seems broken.

I wanted to show you these:
- [On purpose](https://youtu.be/pe3_wKwPj2Q)
- [On naming](https://youtu.be/CpeTfnDc20A)

**Comment by Serosis** [comment]
Everything is in construction mode until I fix up the new, leaner repository.

**Comment by Ala-lala** [comment]
I'm a bit late, but are you sure you want to archive the repository and make an entirely new one? It would break `git blame` (or at least make it a lot harder to use) and other things relying on history, and there are [ways](https://help.github.com/en/articles/removing-sensitive-data-from-a-repository) to remove files from your commit history without making an entirely new repository.

**Comment by Serosis** [comment]
I edited my previous comment, it's much lengthier now.

**Comment by Serosis** [comment]
Once I get all the content compartmentalized it'll be easier to decide on a name for the content packages *or* putting the content inside a folder with the current naming scheme and renaming the repository.

**Comment by Ala-lala** [comment]
Really? I tried removing most of the big binaries in [this clone](https://github.com/Ala-lala/UQM-MegaMod-History-Test) with BFG repo cleaner (with, effectively, `git clone --mirror https://github.com/Ala-lala/UQM-MegaMod-History-Test.git && java -jar bfg-1.13.0.jar --delete-folders mm-hd --delete-files "UrQuanMasters*.exe" UQM-MegaMod-History-Test.git && java -jar bfg-1.13.0.jar --delete-files UrQuanMasters UQM-MegaMod-History-Test.git && java -jar bfg-1.13.0.jar --delete-files "*.uqm" UQM-MegaMod-History-Test.git && java -jar bfg-1.13.0.jar --delete-files "Translation Pack.zip" UQM-MegaMod-History-Test.git && cd UQM-MegaMod-History-Test.git` then `git reflog expire --expire=now --all && git gc --prune=now --aggressive`) and it seems to have worked. I haven't done anything like this before, so I can't be sure I did it correctly, but commit history and current files seem to be preserved, there aren't any duplicate commits, and the repo size when cloning is down to 200MB.

**Comment by Serosis** [comment]
Hmmm... I can probably *still* do that but it won't change what I'm doing to shift the files around in the new repository.

I looked everywhere for a tool that did what BFG repo cleaner does but I only ended up with a script called "git-prune-files".

**Comment by Serosis** [comment]
I'll give this a test tomorrow to see if I can't prune it down further.

**Comment by Serosis** [comment]
Also, in an effort to not use Github as a forum outlet you can find me on _The New Alliance of Free Stars_  Discord server: https://discord.gg/JkqbYMk

Which has a dedicated MegaMod channel.

**Comment by es20490446e** [comment]
Sorry, I don't use communication apps 😉

**Comment by Serosis** [comment]
I tried BFG cleaner and it does the exact same thing as "git-prune-files" (duplicate commit history) only a bit faster. But this time I found out that you have to contact Github support if you want to clean out repositories that have pull requests.

That's a step further than what I'm willing to participate in. So a fresh repo it is.
